version: "3.9"

services:
  api:
    build: .
    container_name: shipping_api
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:root@db:5432/shipping
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: shipping_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: shipping
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: shipping_redis
    ports:
      - "6379:6379"
